### ISSUE TITLE
Don't remove all PSSessions

### ISSUE THREAD

**Issue by bgelens** [Inovativ/SMBblueprint-PowerShell#4]
## Problem
If I have PSSessions open, using the Office deployment will remove them. 

## Expected behavior
It should not remove PSSessions it doesn't create.

## Notes
```powershell
finally{
    get-pssession|Remove-PSSession
    
```
https://github.com/Inovativ/SMBblueprint-PowerShell/blob/dev/SMBBluePrint/functions/public/New-SMBOfficeDeployment.ps1#L244

**Comment by jvmeir** [comment]
This issue was moved to Inovativ/Feedback#13
